#!/bin/bash

set -e

if [ "$UID" != 0 ]; then
    echo "Error: must run this script as root (e.g. with sudo)" >&2
    exit 1
fi

if [ "$#" != 1 ] || [[ "$1" == -* ]]; then
    echo "Error: usage: $0 https://url/for/mainnet/data.mdb"
    exit 1
fi

if ! [ -e /var/lib/quenero ]; then
    echo "/var/lib/quenero does not exist; did you properly install the quenerod package?"
    exit 1
fi

if ! [ -e /var/lib/quenero/lmdb ]; then
    mkdir /var/lib/quenero/lmdb
    chown _loki:_loki /var/lib/quenero/lmdb
fi

echo "Ready to download lmdb from $1."
if [ -e /var/lib/quenero/lmdb/data.mdb ]; then
    echo "Will overwrite existing data.mdb:"
    ls -l --si /var/lib/quenero/lmdb/data.mdb
fi

echo

read -p "Press enter to continue, ^C to abort"

curl "$1" >/var/lib/quenero/lmdb/data.mdb

chown _loki:_loki /var/lib/quenero/lmdb/data.mdb
echo "Downloaded data.mdb:"
ls -l --si /var/lib/quenero/lmdb/data.mdb
